### ISSUE TITLE
How to read output

### ISSUE THREAD

**Issue by krivadna** [0xKayala/ParamSpider#1]
Total number of retries:  0                                                                    [+] Total unique urls found : 43857                                                                [+] Output is saved here   : output/zomato.com.txt

Where do we find the output file and can we view from inside termux terminal

**Comment by MU2324** [comment]
cat output/zomato.com.txt

**Comment by 0xKayala** [comment]
Firstly, The tool is created for Kali or any other Linux Oriented Operating System. In termux the default or home directory will be different. So, you need to adjust the paths in the script before you can use this tool on termux. Only then it will work. I hope you understood this now.

**Comment by krivadna** [comment]
Thanks for your response. It's not working the reading output.i can send the screenshot

**Comment by 0xKayala** [comment]
If it is not working then you can use the latest paramspider tool of the original author and make the changes in the tool to work on termux
